# Generated by Django 4.0 on 2021-12-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.category'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='uniqCategoryProduct'),
        ),
        migrations.AddConstraint(
            model_name='slider',
            constraint=models.UniqueConstraint(fields=('image', 'productId'), name='uniqImageProduct'),
        ),
    ]
